parameters:
    sylius.security.admin_regex: "^/admin"
    sylius.security.api_regex: "^/api"
    sylius.security.shop_regex: "^/(?!admin|api/.*|api$|media/.*)[^/]++"

security:
    providers:
        sylius_admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based
        sylius_shop_user_provider:
            id: sylius.shop_user_provider.email_or_name_based
    encoders:
        Sylius\Component\User\Model\UserInterface: sha512
    firewalls:
      
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
       
        
        admin:
            switch_user: true
            context: admin
            pattern: "%sylius.security.admin_regex%"
            provider: sylius_admin_user_provider
            form_login:
                provider: sylius_admin_user_provider
                login_path: sylius_admin_login
                check_path: sylius_admin_login_check
                failure_path: sylius_admin_login
                default_target_path: sylius_admin_dashboard
                use_forward: false
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_admin_security_token
                csrf_token_id: admin_authenticate
            remember_me:
                secret: '%kernel.secret%'
                path: /admin
                name: APP_ADMIN_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: sylius_admin_logout
                target: sylius_admin_login
            anonymous: true

#        oauth_token:
#            pattern: "%sylius.security.api_regex%/oauth/v2/token"
#            security: false
        
        oauth_token:
            pattern: "%sylius.security.api_regex%/login_check"
            security: false
            
            
        api_authorization:
            pattern: "%sylius.security.api_regex%/doc"
            security: false
            
        facebook_login_api:
            pattern: "%sylius.security.api_regex%/facebooks/logins"
            security: false 
        
        
        api_registration:
            pattern: "%sylius.security.api_regex%/registers"
            security: false
            
            
            
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: sylius_shop_user_provider
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        
        

        api:
            pattern: "%sylius.security.api_regex%/.*"
            provider: sylius_shop_user_provider
            #fos_oauth: true
            stateless: true
            #anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        shop:
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            context: shop
            pattern: "%sylius.security.shop_regex%"
            provider: sylius_shop_user_provider
            form_login:
                success_handler: sylius.authentication.success_handler
                failure_handler: sylius.authentication.failure_handler
                provider: sylius_shop_user_provider
                login_path: sylius_shop_login
                check_path: sylius_shop_login_check
                failure_path: sylius_shop_login
                default_target_path: sylius_shop_homepage
                use_forward: false
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_shop_security_token
                csrf_token_id: shop_authenticate
            remember_me:
                secret: '%kernel.secret%'
                name: APP_SHOP_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: sylius_shop_logout
                target: sylius_shop_login
                invalidate_session: false
                success_handler: sylius.handler.shop_user_logout
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false



        
        
        
    access_control:
        - { path: ^/api/registers, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/facebooks/logins, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
       
        
#        - { path: "/api", role: IS_AUTHENTICATED_ANONYMOUSLY}
        
        - { path: "%sylius.security.admin_regex%/_partial", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: "%sylius.security.admin_regex%/_partial", role: ROLE_NO_ACCESS }
        - { path: "%sylius.security.shop_regex%/_partial", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: "%sylius.security.shop_regex%/_partial", role: ROLE_NO_ACCESS }

        - { path: "%sylius.security.admin_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: "%sylius.security.api_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%sylius.security.shop_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "%sylius.security.shop_regex%/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%sylius.security.shop_regex%/verify", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "%sylius.security.admin_regex%", role: ROLE_ADMINISTRATION_ACCESS }
        #- { path: "%sylius.security.api_regex%/.*", role: ROLE_API_ACCESS }
        - { path: "%sylius.security.shop_regex%/account", role: ROLE_USER }
