Sylius\Component\Product\Model\Product:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        name:
            expose: false
            groups: [Default, Detailed, Autocomplete]
        id:
            expose: false
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        code:
            expose: false
            type: string
            groups: [Default, Detailed, Autocomplete]
        options:
            expose: false
            type: array
            groups: [Default, Detailed]
        attributes:
            expose: false
            type: array
            groups: [Detailed]
        associations:
            expose: true
            type: array
            groups: [Detailed]
        translations:
            expose: true
            type: array
            groups: [Detailed]
    virtual_properties:
        getName:
            serialized_name: name
            groups: [Default, Detailed, Autocomplete]
    relations:
        -   rel: self
            href:
                route: sylius_admin_api_product_show
                parameters:
                    code: expr(object.getCode())
                    version: 1
        -   rel: variants
            href:
                route: sylius_admin_api_product_variant_index
                parameters:
                    productCode: expr(object.getCode())
                    version: 1
            exclusion:
                groups: [Detailed]